# Hero 2
I have patched the vulnerability, it is safer now right?

## Summary
- **Author:** Gr0undUp
- **Category:** crypto
- **Difficulty:** medium
- **Finals:** False

## Hints
None

## Files
- [Hero 2 chall.py](<dist/Hero 2 chall.py>)

## Flags
- `YBN24{RS4_mu1t!prim3_f4ct0r1ng_bu7_m0r3_:D}` (static, case-sensitive)

## Services
| [`hero-2`](<service/hero-2>) | None | internal |
